name: CI/CD Node.js to GCP

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "18"

      - run: npm install
      - run: npm test

      - name: Deploy to GCP VM
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.SERVER_SSH_PASSPHRASE }}
          script: |
            cd ~/hello-actions || git clone https://github.com/trinotoPixmag/hello-actions.git ~/hello-actions
            cd ~/hello-actions
            git pull origin main
            npm install --production
            pm2 restart hello-actions || pm2 start index.js --name hello-actions
